// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxaWUyukNMPa2ADBfHVZLjmfEXRALuFSU',
    appId: '1:973147448820:web:a227f9734657da128005a1',
    messagingSenderId: '973147448820',
    projectId: 'pizzatopia-9ef7a',
    authDomain: 'pizzatopia-9ef7a.firebaseapp.com',
    storageBucket: 'pizzatopia-9ef7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8gaV8OOEi2shAs8w9hSwhGFzU66P7gpg',
    appId: '1:973147448820:android:6b5bde374b60bf508005a1',
    messagingSenderId: '973147448820',
    projectId: 'pizzatopia-9ef7a',
    storageBucket: 'pizzatopia-9ef7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdi_rUzSMPBgZOPUR3sYQdIVlRDDmr4G8',
    appId: '1:973147448820:ios:47540b5512cf317e8005a1',
    messagingSenderId: '973147448820',
    projectId: 'pizzatopia-9ef7a',
    storageBucket: 'pizzatopia-9ef7a.appspot.com',
    iosBundleId: 'com.example.pizzatopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdi_rUzSMPBgZOPUR3sYQdIVlRDDmr4G8',
    appId: '1:973147448820:ios:47540b5512cf317e8005a1',
    messagingSenderId: '973147448820',
    projectId: 'pizzatopia-9ef7a',
    storageBucket: 'pizzatopia-9ef7a.appspot.com',
    iosBundleId: 'com.example.pizzatopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxaWUyukNMPa2ADBfHVZLjmfEXRALuFSU',
    appId: '1:973147448820:web:ee70a2a2a989326c8005a1',
    messagingSenderId: '973147448820',
    projectId: 'pizzatopia-9ef7a',
    authDomain: 'pizzatopia-9ef7a.firebaseapp.com',
    storageBucket: 'pizzatopia-9ef7a.appspot.com',
  );
}
